### PR TITLE
fix a bug when inference

### PR DESCRIPTION
**Pull request by wkcn**
Hi there, I fix a bug
```
➜  WeightNet git:(master) python inference.py 
Traceback (most recent call last):
  File "inference.py", line 19, in <module>
    import model as M
ModuleNotFoundError: No module named 'model'

```

### CODE REVIEW

**Comment by nmaac** [comment]
updated required files

**Comment by wkcn** [comment]
Is my commit outdated?
```
commit 61ea83746ec187e190f1cf9daf9d2a08c867c351 (HEAD -> fix_inference, me/fix_inference)
Author: wkcn <wkcn@live.cn>
Date:   Tue Jul 28 21:23:10 2020 +0800

    fix inference
```
```
commit 860c64bca8f75e54378f3885181eaaf5e66c9d46 (HEAD -> master, origin/master, origin/HEAD)
Author: maningning <maningning@megvii.com>
Date:   Tue Jul 28 21:40:08 2020 +0800

    update files

```

**Comment by 0xMashiro** [comment]
> updated required files

You should merge this pull request then do some new updates.

**Comment by 0xMashiro** [comment]
> Is my commit outdated?
> 
> ```
> commit 61ea83746ec187e190f1cf9daf9d2a08c867c351 (HEAD -> fix_inference, me/fix_inference)
> Author: wkcn <wkcn@live.cn>
> Date:   Tue Jul 28 21:23:10 2020 +0800
> 
>     fix inference
> ```
> 
> ```
> commit 860c64bca8f75e54378f3885181eaaf5e66c9d46 (HEAD -> master, origin/master, origin/HEAD)
> Author: maningning <maningning@megvii.com>
> Date:   Tue Jul 28 21:40:08 2020 +0800
> 
>     update files
> ```

Hey guys, take it easy. I guess the author get your idea but he may not be familiar with git.

**Pull request closed without merging**
